perl ./tools/html2c.pl password.htm              1
perl ./tools/html2c.pl passwordConfirmation.htm  1
perl ./tools/html2c.pl duplicate.htm             1
perl ./tools/html2c.pl index.htm                 1
perl ./tools/html2c.pl top.htm                   1
perl ./tools/html2c.pl bg.gif                   -1
perl ./tools/html2c.pl upload.htm                1
perl ./tools/html2c.pl uploaddone.htm            0
perl ./tools/html2c.pl left.htm                  1
perl ./tools/html2c.pl sys.htm                   0
perl ./tools/html2c.pl postdemo.htm              0
perl ./tools/html2c.pl get.htm                   1