//path_param.h
/*
*4600导轨和墨车参数
*1，导轨
*2, 墨车
*3，墨站
*/
#ifndef __PATH_PARAM_H
#define __PATH_PARAM_H

#define ORIGIN_TO_INK_STOP_NEAR_LEN_MM  	(u16)(27)
/*转化为以0.0423mm 为单位, 相邻两个光栅格距离的1/4*/
#define ORIGIN_TO_INK_STOP_NEAR_LEN_EDGE   (long)(ORIGIN_TO_INK_STOP_NEAR_LEN_MM*ENCODER_PPR_LINE*10/( 254))
	
#define INK_STOP_LEN_MM   	   (u16)(240) 	 	/*墨站的长度*/
#define INK_STOP_LEN_EDGE	   (long)(INK_STOP_LEN_MM*ENCODER_PPR_LINE*10/( 254))

#define PRINT_AREA_LEN_MM  	(u16) (1545) 		/*有效打印区长度*/
#define PRINT_AREA_LEN_EDGE	(long)(PRINT_AREA_LEN_MM*ENCODER_PPR_LINE*10/( 254))

#define PRINT_AREA_NEAR_TO_INK_STOP_FAR_LEN_MM  60 	 /*打印区近边和墨站远边间距*/
#define PRINT_AREA_NEAR_TO_INK_STOP_FAR_LEN_EDGE	(long)(PRINT_AREA_NEAR_TO_INK_STOP_FAR_LEN_MM*ENCODER_PPR_LINE*10/( 254))

#define FAR_SPEED_UP_AREA_LEN_MM  (u16)(257)  	/*远端加速区长度*/
#define FAR_SPEED_UP_AREA_LEN_EDGE	(long)(FAR_SPEED_UP_AREA_LEN_MM*ENCODER_PPR_LINE*10/( 254))

#define PRINT_ORIGIN_DEFAULT_LEN_MM    (u16)(40) 
#define PRINT_ORIGIN_DEFAULT_LEN_EDGE   (long)(PRINT_ORIGIN_DEFAULT_LEN_MM*ENCODER_PPR_LINE*10/( 254))

#define STOP_NEAR_TO_INK_STOP_LEN_MM 	(u16)(14)		/*近端停车点到墨站近端点的距离*/
#define STOP_NEAR_TO_INK_STOP_LEN_EDGE   (long)(STOP_NEAR_TO_INK_STOP_LEN_MM*ENCODER_PPR_LINE*10/( 254))/*近端停车点到墨站近端点的距离*/

#define STOP_NEAR_TO_INK_STOP_LEN_MM 	(u16)(14)		/*近端停车点到墨站近端点的距离*/
#define STOP_NEAR_TO_INK_STOP_LEN_EDGE   (long)(STOP_NEAR_TO_INK_STOP_LEN_MM*ENCODER_PPR_LINE*10/( 254))/*近端停车点到墨站近端点的距离*/

#endif


